[fortress.ign-common4]
do_check = false
propagated = [ "gts" ]

[fortress.ign-fuel-tools7]
do_check = false

[fortress.ign-gazebo6]
do_check = false

[fortress.ign-gui6]
do_check = false

[fortress.ign-launch5]
do_check = false

[fortress.ign-msgs8]

[fortress.ign-physics5]
do_check = false

[fortress.ign-plugin1]
do_check = false

[fortress.ign-rendering6]
do_check = false
propagated = [ "boost" ]

[fortress.ign-sensors6]
do_check = false

[fortress.ign-transport11]
do_check = false
propagated = [ "libsodium" ]

[fortress.sdformat12]
do_check = false

[harmonic.gz-common5]
do_check = false

[harmonic.gz-fuel-tools9]
do_check = false

[harmonic.gz-gui8]
do_check = false

[harmonic.gz-launch7]
do_check = false

[harmonic.gz-msgs10]
do_check = false

[harmonic.gz-physics7]
do_check = false

[harmonic.gz-plugin2]
do_check = false

[harmonic.gz-rendering8]
do_check = false
propagated = [ "boost" ]

[harmonic.gz-sensors8]
do_check = false

[harmonic.gz-sim8]
do_check = false

[harmonic.gz-tools2]
do_check = false

[harmonic.gz-transport13]
do_check = false
propagated = [ "libsodium" ]

[harmonic.sdformat14]
do_check = false

[ionic.gz-common6]
do_check = false
propagated = [ "libz" ]

[ionic.gz-fuel-tools10]
do_check = false

[ionic.gz-gui9]
do_check = false

[ionic.gz-launch8]
do_check = false

[ionic.gz-msgs11]
do_check = false

[ionic.gz-physics8]
do_check = false

[ionic.gz-plugin3]
do_check = false

[ionic.gz-rendering9]
do_check = false
propagated = [ "boost", "libz", "python3" ]

[ionic.gz-sensors9]
do_check = false

[ionic.gz-sim9]
do_check = false

[ionic.gz-tools2]
do_check = false

[ionic.gz-transport14]
do_check = false
propagated = [ "libsodium" ]

[ionic.sdformat15]
do_check = false

[jetty.gz-cmake5]

[jetty.gz-common7]
do_check = false
propagated = [ "libz" ]

[jetty.gz-fuel-tools11]
do_check = false

[jetty.gz-sim10]
do_check = false

[jetty.gz-gui10]
do_check = false

[jetty.gz-launch9]
do_check = false

[jetty.gz-math9]

[jetty.gz-msgs12]
do_check = false

[jetty.gz-physics9]
do_check = false

[jetty.gz-plugin4]
do_check = false

[jetty.gz-rendering10]
propagated = [ "boost", "libz", "python3" ]
do_check = false

[jetty.gz-sensors10]
do_check = false

[jetty.gz-tools2]
do_check = false

[jetty.gz-transport15]
propagated = [ "libsodium" ]
do_check = false

[jetty.gz-utils4]

[jetty.sdformat16]
do_check = false
