[humble."agimus-project/agimus_controller"]
branch = "fork"
[humble."agimus-project/agimus-demos"]
branch = "fork"
[humble."agimus-project/agimus_franka_description"]
branch = "fork"
do_check = false
[humble."agimus-project/agimus_franka_ros2"]
branch = "fork"
do_check = false
[humble."agimus-project/agimus_libfranka"]
branch = "fork"
do_check = false
[humble."agimus-project/agimus-libfranka-common"]
branch = "fork"
do_check = false
[humble."agimus-project/agimus_msgs"]

[humble."gbartyzel/ros2_net_ft_driver"]
branch = "humble"
packages = {"net_ft_driver" = {native = ["pkg-config"], propagated = ["curl", "curlpp"]}}

[humble."jpgtzg/omni_drive_controller".packages]
omni_drive_controller = {do_check = false}

[humble."loco-3d/linear-feedback-controller"]
[humble."loco-3d/linear-feedback-controller-msgs"]

[humble."pal-robotics/pal_pro_gripper".packages]
pal_pro_gripper_description = {do_check = false}
pal_pro_gripper_controller_configuration = {do_check = false}

[humble."pal-robotics/pal_sea_arm".packages]
pal_sea_arm_controller_configuration = {do_check = false}
pal_sea_arm_description = {do_check = false}

[humble."pal-robotics/pal_sea_arm_moveit_config".packages]
pal_sea_arm_moveit_config = {do_check = false}

[humble."pal-robotics/pal_sea_arm_simulation"]

[humble."pal-robotics/realsense_gazebo_plugin".packages]
realsense_gazebo_plugin = {do_check = false}

[humble."pal-robotics/realsense_simulation".packages]
realsense_simulation = {do_check = false}

[humble."pal-robotics/tiago_pro_head_robot".packages]
tiago_pro_head_bringup = {do_check = false}
tiago_pro_head_controller_configuration = {do_check = false}
tiago_pro_head_description = {do_check = false}

[humble."pal-robotics/tiago_pro_head_simulation"]

[humble."pal-robotics/tiago_pro_moveit_config".packages]
tiago_pro_moveit_config = {do_check = false}

[humble."pal-robotics/tiago_pro_navigation".packages]
tiago_pro_2dnav = {do_check = false}
tiago_pro_laser_sensors = {do_check = false}

[humble."pal-robotics/tiago_pro_robot".packages]
tiago_pro_bringup = {do_check = false}
tiago_pro_controller_configuration = {do_check = false}
tiago_pro_description = {do_check = false}

[humble."pal-robotics/tiago_pro_simulation".packages]
tiago_pro_gazebo = {do_check = false}

[jazzy."agimus-project/agimus_controller"]
branch = "fork"
[jazzy."agimus-project/agimus_franka_description"]
branch = "fork"
do_check = false
[jazzy."agimus-project/agimus_msgs"]

[jazzy."loco-3d/linear-feedback-controller"]
[jazzy."loco-3d/linear-feedback-controller-msgs"]

[jazzy."ros-controls/ros2_control_demos"]
branch = "jazzy"
[jazzy."ros-controls/ros2_control_demos".packages.example_1]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_2]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_3]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_4]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_5]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_6]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_7]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_8]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_9]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_10]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_11]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_12]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_13]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_14]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_15]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_16]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_17]
do_check = false

[jazzy."Tiago-Harmonic/tiago_harmonic"]
[jazzy."Tiago-Harmonic/tiago_simulation".packages]
tiago_gazebo = {do_check = false}
[jazzy."Tiago-Harmonic/pal_urdf_utils"]
do_check = false
[jazzy."Tiago-Harmonic/omni_base_robot".packages]
omni_base_controller_configuration = {do_check = false}
omni_base_description = {do_check = false}
omni_base_bringup = {do_check = false}
[jazzy."Tiago-Harmonic/tiago_moveit_config"]
do_check = false
[jazzy."Tiago-Harmonic/pal_robotiq_gripper".packages]
pal_robotiq_controller_configuration = {do_check = false}
pal_robotiq_description = {do_check = false}
pal_robotiq_gripper = {do_check = false}
[jazzy."Tiago-Harmonic/pal_gripper".packages]
pal_gripper_controller_configuration = {do_check = false}
pal_gripper_description = {do_check = false}
pal_gripper_simulation = {do_check = false}
[jazzy."Tiago-Harmonic/pal_hey5".packages]
pal_hey5_controller_configuration = {do_check = false}
pal_hey5_description = {do_check = false}
[jazzy."Tiago-Harmonic/tiago_navigation".packages]
tiago_2dnav = {do_check = false}
tiago_laser_sensors = {do_check = false}
[jazzy."Tiago-Harmonic/tiago_robot".packages]
tiago_controller_configuration = {do_check = false}
tiago_description = {do_check = false}
tiago_bringup = {do_check = false}
[jazzy."Tiago-Harmonic/pmb2_navigation".packages]
pmb2_laser_sensors = {do_check = false}
pmb2_2dnav = {do_check = false}
[jazzy."Tiago-Harmonic/pmb2_robot".packages]
pmb2_controller_configuration = {do_check = false}
pmb2_description = {do_check = false}
pmb2_bringup = {do_check = false}
[jazzy."Tiago-Harmonic/play_motion2"]
do_check = false
[jazzy."Tiago-Harmonic/br2_gazebo_worlds"]
do_check = false
[jazzy."Tiago-Harmonic/tiago_moveitpy"]
[jazzy."Tiago-Harmonic/twist_mux"]
do_check = false
[jazzy."Tiago-Harmonic/pal_maps"]
[jazzy."Tiago-Harmonic/pal_gazebo_worlds"]
do_check = false
[jazzy."Tiago-Harmonic/launch_pal"]

[kilted."agimus-project/agimus_controller"]
branch = "fork"
[kilted."agimus-project/agimus_franka_description"]
branch = "fork"
do_check = false
[kilted."agimus-project/agimus_msgs"]
[kilted."loco-3d/linear-feedback-controller"]
[kilted."loco-3d/linear-feedback-controller-msgs"]

[rolling."agimus-project/agimus_controller"]
branch = "fork"
[rolling."agimus-project/agimus_franka_description"]
branch = "fork"
do_check = false
[rolling."agimus-project/agimus_msgs"]
[rolling."loco-3d/linear-feedback-controller"]
[rolling."loco-3d/linear-feedback-controller-msgs"]
